name: ${project.name}
version: ${project.version}
api-version: 1.13
main: ${project.groupId}.${project.artifactId}.NetworkInterceptor
description: ${project.description}
authors: [drives_a_ford, Luck, SlimeDog]
load: STARTUP
loadbefore: [LuckPerms]
depend: []
softdepend: []
folia-supported: true

commands:
  networkinterceptor:
    description: Main plugin command
    usage: /<command> reload
    aliases: [ni]
    permission: networkinterceptor.command

permissions:
  networkinterceptor.command:
    description: Allows using the main command
    default: op
  networkinterceptor.command.reload:
    description: Allows reloading the config
    default: op
  networkinterceptor.command.info:
    description: Allows showing info (similar to startup)
    default: op
